### ISSUE TITLE
Unable to prepare env

### ISSUE THREAD

**Issue by dciborow** [Azure/MachineLearningSamples-DistributedHyperParameterTuning#6]
When running...
az ml experiment prepare

Getting an error...

Collecting azureml.primitives (from azureml.pyrecipes.dataframe==1.0.12)
  Could not find a version that satisfies the requirement azureml.primitives (from azureml.pyrecipes.dataframe==1.0.12) (from versions: )
No matching distribution found for azureml.primitives (from azureml.pyrecipes.dataframe==1.0.12)

CondaValueError: pip returned an error.

**Comment by akshaya-a** [comment]
Fixed with #8
